name: 'Khulnasoft pipeline runner'
description: 'Github action that runs khulnasoft pipeline'
author: 'khulnasoft'
inputs:
  args:
    description: 'khulnasoft cli build variables, see https://khulnasoft.github.io/cli/pipelines/run-pipeline/#setting-variables-through-the-command for more information.'
    required: false
branding:
  icon: 'arrow-right-circle'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
